;;; tmux-resume.el --- Editor checkpoints for tmux-resume -*- lexical-binding: t; -*-
;; No user buffer is written by this helper. It can be loaded from init.el,
;; interactively with load-file, or on demand through an existing Emacs server.
(require 'json)
(require 'cl-lib)

(defvar tmux-resume--root
  (expand-file-name "tmux-resume/emacs/"
                    (or (getenv "XDG_STATE_HOME") "~/.local/state/")))
(defvar tmux-resume--timer nil)
(defvar tmux-resume--start
  (with-temp-buffer
    (insert-file-contents "/proc/self/stat")
    (nth 19 (split-string (replace-regexp-in-string "\\`.*) " "" (buffer-string))))))

(defun tmux-resume--base ()
  (expand-file-name (number-to-string (emacs-pid)) tmux-resume--root))

(defun tmux-resume--publish (data)
  (make-directory tmux-resume--root t)
  (set-file-modes tmux-resume--root #o700)
  (let* ((file (concat (tmux-resume--base) ".json"))
         (temporary (concat file ".tmp")))
    (with-temp-file temporary (insert (json-encode data)))
    (set-file-modes temporary #o600)
    (rename-file temporary file t)))

(defun tmux-resume--unsaved-p ()
  (let ((generated (and buffer-read-only
                        (or (derived-mode-p 'special-mode)
                            (equal (buffer-name) "*Async-native-compile-log*")))))
    (and (buffer-modified-p)
         (or buffer-file-name (and (> (buffer-size) 0) (not generated))))))

(defun tmux-resume-checkpoint (directory nonce)
  "Report buffer state and save file positions/window layout to DIRECTORY."
  (let ((buffers nil) (files nil) (error-text "")
        (state (window-state-get (frame-root-window) t)))
    (dolist (buffer (buffer-list))
      (with-current-buffer buffer
        (unless (and (null buffer-file-name) (string-prefix-p " " (buffer-name)))
          (push `((name . ,(or buffer-file-name (buffer-name)))
                  (modified . ,(if (tmux-resume--unsaved-p) t :json-false))) buffers)
          (when (get-buffer-process buffer)
            (setq error-text "process/terminal buffers cannot be restored as running jobs"))
          (when buffer-file-name
            (push (list buffer-file-name (point)) files)))))
    (condition-case error-data
        (let ((file (expand-file-name "session.el" directory)))
          (with-temp-file file
            (insert ";; Generated by tmux-resume: reopen saved files only.\n")
            (insert "(setq inhibit-startup-screen t)\n")
            (dolist (entry files)
              (prin1 `(with-current-buffer (find-file-noselect ,(car entry))
                        (goto-char (min (point-max) ,(cadr entry)))) (current-buffer))
              (insert "\n"))
            (prin1 `(window-state-put ',state (frame-root-window) 'safe) (current-buffer))
            (insert "\n"))
          (set-file-modes file #o600))
      (error (setq error-text (error-message-string error-data))))
    (tmux-resume--publish `((pid . ,(emacs-pid)) (start . ,tmux-resume--start)
                           (nonce . ,nonce) (buffers . ,(vconcat buffers))
                           (error . ,error-text)))))

(defun tmux-resume--tick ()
  (let ((request (concat (tmux-resume--base) ".request.json")))
    (when (file-readable-p request)
      (condition-case nil
          (let* ((json-object-type 'alist)
                 (data (json-read-file request)))
            (delete-file request)
            (tmux-resume-checkpoint (alist-get 'directory data) (alist-get 'nonce data)))
        (error nil)))))

(defun tmux-resume--cleanup ()
  (dolist (suffix '(".json" ".request.json"))
    (let ((file (concat (tmux-resume--base) suffix)))
      (when (file-exists-p file) (delete-file file)))))

(tmux-resume--publish `((pid . ,(emacs-pid)) (start . ,tmux-resume--start)))
(unless (timerp tmux-resume--timer)
  (setq tmux-resume--timer (run-at-time 0.2 0.2 #'tmux-resume--tick)))
(add-hook 'kill-emacs-hook #'tmux-resume--cleanup)
(provide 'tmux-resume)
;;; tmux-resume.el ends here
